/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull
import org.slf4j.LoggerFactory

class AppTest {
    companion object {
        private val logger = LoggerFactory.getLogger(AppTest::class.java)
    }

    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        println("Hello, Kotlin!")
        logger.info("Hello, Kotlin!")
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
