/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull
import org.slf4j.LoggerFactory

class AppTests {
    companion object {
        private val logger = LoggerFactory.getLogger(AppTests::class.java)
    }

    @Test fun appHasGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

}
