/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull
import org.slf4j.LoggerFactory

class HelloTests {
    companion object {
        private val logger = LoggerFactory.getLogger(HelloTests::class.java)
    }

    @Test fun hello() {
        println("Hello, Kotlin!")
        logger.info("Hello, Kotlin!")
    }

    @Test fun appHasGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

}
