/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull
import org.slf4j.LoggerFactory

class MemberRefOperatorTests {
    companion object {
        private val logger = LoggerFactory.getLogger(MemberRefOperatorTests::class.java)
    }

    /**
     * `::` creates a member(property and function) reference or a class reference.
     * `peroperty` is class member variable
     *
     * Operators and special symbols - https://kotlinlang.org/docs/keyword-reference.html#operators-and-special-symbols
     * Callable references (function, property) - https://kotlinlang.org/docs/reflection.html#callable-references
     * Class references - https://kotlinlang.org/docs/reflection.html#class-references 
     */

    @Test fun funcRefTest() {
        fun greet() = println("Hello")
        val greetRef = ::greet // create reference of function
        greetRef() // print "Hello"
    }

    // property = class member variable
    val property = "MemberVariable"
    @Test fun propertyRefTest() {
        val propertyRef = ::property            // OK
        println(propertyRef.get()) // "Kotlin"

        val localVariable = "Local"
        // val localVarRef = ::localVariable    // Error
        // println(localVarRef.get())
    }
}
